server:
  port: 8089

spring:
  application:
    name: coreAuthorisationService
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/postme?useSSL=false
    username: root
    password:

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true


postme:
  app:
    cookie:
      jwtCookieName: auth
      jwtSecret: generatedApiKey
      jwtExpirationMs: 86400000
      authPath: /
  api:
    version: v1