server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gatewayService

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaUser:pass@localhost:8761/eureka/

zuul:
  routes:
    authService:
      path: /v1/auth/**
      url: http://localhost:8081/v1/auth
      sensitiveHeaders:
        -

    testService:
      path: /v1/test/**
      url: http://localhost:8082/v1/test
      sensitiveHeaders:
        -