server:
  port: 8761

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: core
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/postme?useSSL=false
    username: root
    password:

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://userEureka:password@localhost:8761/eureka